package com.TheJobCoach.webapp.util.shared;

public class UserValuesConstantsPerformance 
{
	public final static String PERFORMANCE_CREATEOPPORTUNITY_MONTHLY         = "PERFORMANCE_CREATEOPPORTUNITY_MONTHLY";
	public final static String PERFORMANCE_CREATEOPPORTUNITY_WEEKLY          = "PERFORMANCE_CREATEOPPORTUNITY_WEEKLY";
	public final static String PERFORMANCE_CANDIDATEOPPORTUNITY_MONTHLY      = "PERFORMANCE_CANDIDATEOPPORTUNITY_MONTHLY";
	public final static String PERFORMANCE_CANDIDATEOPPORTUNITY_WEEKLY       = "PERFORMANCE_CANDIDATEOPPORTUNITY_WEEKLY";
	public final static String PERFORMANCE_INTERVIEW_MONTHLY                 = "PERFORMANCE_INTERVIEW_MONTHLY";
	public final static String PERFORMANCE_INTERVIEW_WEEKLY                  = "PERFORMANCE_INTERVIEW_WEEKLY";
	public final static String PERFORMANCE_PHONECALL_MONTHLY                 = "PERFORMANCE_PHONECALL_MONTHLY";
	public final static String PERFORMANCE_PHONECALL_WEEKLY                  = "PERFORMANCE_PHONECALL_WEEKLY";
	public final static String PERFORMANCE_CONNECT_WEEKLY                    = "PERFORMANCE_CONNECT_WEEKLY";
}
