package com.TheJobCoach.webapp.util.shared;

public class UserValuesConstantsMyGoals 
{
	public final static String PERFORMANCE_CREATEOPPORTUNITY_BIWEEKLY        = "PERFORMANCE_CREATEOPPORTUNITY_BIWEEKLY";
	public final static String PERFORMANCE_CREATEOPPORTUNITY_MONTHLY         = "PERFORMANCE_CREATEOPPORTUNITY_MONTHLY";
	public final static String PERFORMANCE_CREATEOPPORTUNITY_WEEKLY          = "PERFORMANCE_CREATEOPPORTUNITY_WEEKLY";

	public final static String PERFORMANCE_CANDIDATEOPPORTUNITY_BIWEEKLY     = "PERFORMANCE_CANDIDATEOPPORTUNITY_BIWEEKLY";
	public final static String PERFORMANCE_CANDIDATEOPPORTUNITY_MONTHLY      = "PERFORMANCE_CANDIDATEOPPORTUNITY_MONTHLY";
	public final static String PERFORMANCE_CANDIDATEOPPORTUNITY_WEEKLY       = "PERFORMANCE_CANDIDATEOPPORTUNITY_WEEKLY";
	
	public final static String PERFORMANCE_INTERVIEW_BIWEEKLY                = "PERFORMANCE_INTERVIEW_BIWEEKLY";
	public final static String PERFORMANCE_INTERVIEW_MONTHLY                 = "PERFORMANCE_INTERVIEW_MONTHLY";
	public final static String PERFORMANCE_INTERVIEW_WEEKLY                  = "PERFORMANCE_INTERVIEW_WEEKLY";
	
	public final static String PERFORMANCE_PHONECALL_BIWEEKLY                = "PERFORMANCE_PHONECALL_BIWEEKLY";
	public final static String PERFORMANCE_PHONECALL_MONTHLY                 = "PERFORMANCE_PHONECALL_MONTHLY";
	public final static String PERFORMANCE_PHONECALL_WEEKLY                  = "PERFORMANCE_PHONECALL_WEEKLY";

	public final static String PERFORMANCE_PROPOSAL_BIWEEKLY                = "PERFORMANCE_PROPOSAL_BIWEEKLY";
	public final static String PERFORMANCE_PROPOSAL_MONTHLY                 = "PERFORMANCE_PROPOSAL_MONTHLY";
	public final static String PERFORMANCE_PROPOSAL_WEEKLY                  = "PERFORMANCE_PROPOSAL_WEEKLY";

	public final static String PERFORMANCE_RECALL_GOAL_MIDDLE                = "PERFORMANCE_RECALL_GOAL_MIDDLE";
	
	public final static String PERFORMANCE_CONNECT_BEFORE_HOUR               = "PERFORMANCE_CONNECT_BEFORE_HOUR";
	public final static String PERFORMANCE_CONNECT_NOT_AFTER_HOUR            = "PERFORMANCE_CONNECT_NOT_AFTER_HOUR";
	public final static String PERFORMANCE_CONNECT_WEEKLY_RATIO              = "PERFORMANCE_CONNECT_WEEKLY";
	public final static String PERFORMANCE_CONNECT_MONTHLY_RATIO             = "PERFORMANCE_CONNECT_MONTHLY";
}
